# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/kokoro_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/kokoro_api.proto\x12\x19\x64\x65vtools.kokoro.api.proto\"\xc2\x03\n\x0c\x42uildRequest\x12\x15\n\rfull_job_name\x18\x01 \x01(\t\x12<\n\x0cscm_revision\x18\x03 \x01(\x0b\x32&.devtools.kokoro.api.proto.ScmRevision\x12G\n\x12multi_scm_revision\x18\t \x01(\x0b\x32+.devtools.kokoro.api.proto.MultiScmRevision\x12\x18\n\x10input_file_paths\x18\x04 \x03(\t\x12\x46\n\x08\x65nv_vars\x18\x06 \x03(\x0b\x32\x34.devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry\x12N\n\x0c\x62uild_params\x18\x0c \x03(\x0b\x32\x38.devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x42uildParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"i\n\x0bScmRevision\x12K\n\x13github_scm_revision\x18\x04 \x01(\x0b\x32,.devtools.kokoro.api.proto.GithubScmRevisionH\x00\x42\r\n\x0bscmrevision\"\xb0\x01\n\x10MultiScmRevision\x12Q\n\x18git_on_borg_scm_revision\x18\x02 \x03(\x0b\x32/.devtools.kokoro.api.proto.GitOnBorgScmRevision\x12I\n\x13github_scm_revision\x18\x04 \x03(\x0b\x32,.devtools.kokoro.api.proto.GithubScmRevision\"\x8d\x01\n\x11GithubScmRevision\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\ncommit_sha\x18\x01 \x01(\t\x12\x1b\n\x13pull_request_number\x18\x02 \x01(\t\x12\x16\n\x0erepository_url\x18\x03 \x01(\t\x12\r\n\x05owner\x18\x05 \x01(\t\x12\x12\n\nrepository\x18\x06 \x01(\t\"^\n\x14GitOnBorgScmRevision\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04sha1\x18\x01 \x01(\t\x12\x14\n\x0crevision_url\x18\x05 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x04 \x01(\tJ\x04\x08\x02\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.kokoro_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUILDREQUEST_ENVVARSENTRY._options = None
  _BUILDREQUEST_ENVVARSENTRY._serialized_options = b'8\001'
  _BUILDREQUEST_BUILDPARAMSENTRY._options = None
  _BUILDREQUEST_BUILDPARAMSENTRY._serialized_options = b'8\001'
  _BUILDREQUEST._serialized_start=55
  _BUILDREQUEST._serialized_end=505
  _BUILDREQUEST_ENVVARSENTRY._serialized_start=407
  _BUILDREQUEST_ENVVARSENTRY._serialized_end=453
  _BUILDREQUEST_BUILDPARAMSENTRY._serialized_start=455
  _BUILDREQUEST_BUILDPARAMSENTRY._serialized_end=505
  _SCMREVISION._serialized_start=507
  _SCMREVISION._serialized_end=612
  _MULTISCMREVISION._serialized_start=615
  _MULTISCMREVISION._serialized_end=791
  _GITHUBSCMREVISION._serialized_start=794
  _GITHUBSCMREVISION._serialized_end=935
  _GITONBORGSCMREVISION._serialized_start=937
  _GITONBORGSCMREVISION._serialized_end=1031
# @@protoc_insertion_point(module_scope)
