# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/kokoro_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/kokoro_api.proto\x12\x19\x64\x65vtools.kokoro.api.proto\"\xc2\x03\n\x0c\x42uildRequest\x12\x15\n\rfull_job_name\x18\x01 \x01(\t\x12<\n\x0cscm_revision\x18\x03 \x01(\x0b\x32&.devtools.kokoro.api.proto.ScmRevision\x12G\n\x12multi_scm_revision\x18\t \x01(\x0b\x32+.devtools.kokoro.api.proto.MultiScmRevision\x12\x18\n\x10input_file_paths\x18\x04 \x03(\t\x12\x46\n\x08\x65nv_vars\x18\x06 \x03(\x0b\x32\x34.devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry\x12N\n\x0c\x62uild_params\x18\x0c \x03(\x0b\x32\x38.devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x42uildParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"i\n\x0bScmRevision\x12K\n\x13github_scm_revision\x18\x04 \x01(\x0b\x32,.devtools.kokoro.api.proto.GithubScmRevisionH\x00\x42\r\n\x0bscmrevision\"]\n\x10MultiScmRevision\x12I\n\x13github_scm_revision\x18\x04 \x03(\x0b\x32,.devtools.kokoro.api.proto.GithubScmRevision\"\x8d\x01\n\x11GithubScmRevision\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\ncommit_sha\x18\x01 \x01(\t\x12\x1b\n\x13pull_request_number\x18\x02 \x01(\t\x12\x16\n\x0erepository_url\x18\x03 \x01(\t\x12\r\n\x05owner\x18\x05 \x01(\t\x12\x12\n\nrepository\x18\x06 \x01(\t')



_BUILDREQUEST = DESCRIPTOR.message_types_by_name['BuildRequest']
_BUILDREQUEST_ENVVARSENTRY = _BUILDREQUEST.nested_types_by_name['EnvVarsEntry']
_BUILDREQUEST_BUILDPARAMSENTRY = _BUILDREQUEST.nested_types_by_name['BuildParamsEntry']
_SCMREVISION = DESCRIPTOR.message_types_by_name['ScmRevision']
_MULTISCMREVISION = DESCRIPTOR.message_types_by_name['MultiScmRevision']
_GITHUBSCMREVISION = DESCRIPTOR.message_types_by_name['GithubScmRevision']
BuildRequest = _reflection.GeneratedProtocolMessageType('BuildRequest', (_message.Message,), {

  'EnvVarsEntry' : _reflection.GeneratedProtocolMessageType('EnvVarsEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUILDREQUEST_ENVVARSENTRY,
    '__module__' : 'protos.kokoro_api_pb2'
    # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry)
    })
  ,

  'BuildParamsEntry' : _reflection.GeneratedProtocolMessageType('BuildParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _BUILDREQUEST_BUILDPARAMSENTRY,
    '__module__' : 'protos.kokoro_api_pb2'
    # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry)
    })
  ,
  'DESCRIPTOR' : _BUILDREQUEST,
  '__module__' : 'protos.kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.BuildRequest)
  })
_sym_db.RegisterMessage(BuildRequest)
_sym_db.RegisterMessage(BuildRequest.EnvVarsEntry)
_sym_db.RegisterMessage(BuildRequest.BuildParamsEntry)

ScmRevision = _reflection.GeneratedProtocolMessageType('ScmRevision', (_message.Message,), {
  'DESCRIPTOR' : _SCMREVISION,
  '__module__' : 'protos.kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.ScmRevision)
  })
_sym_db.RegisterMessage(ScmRevision)

MultiScmRevision = _reflection.GeneratedProtocolMessageType('MultiScmRevision', (_message.Message,), {
  'DESCRIPTOR' : _MULTISCMREVISION,
  '__module__' : 'protos.kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.MultiScmRevision)
  })
_sym_db.RegisterMessage(MultiScmRevision)

GithubScmRevision = _reflection.GeneratedProtocolMessageType('GithubScmRevision', (_message.Message,), {
  'DESCRIPTOR' : _GITHUBSCMREVISION,
  '__module__' : 'protos.kokoro_api_pb2'
  # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.GithubScmRevision)
  })
_sym_db.RegisterMessage(GithubScmRevision)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUILDREQUEST_ENVVARSENTRY._options = None
  _BUILDREQUEST_ENVVARSENTRY._serialized_options = b'8\001'
  _BUILDREQUEST_BUILDPARAMSENTRY._options = None
  _BUILDREQUEST_BUILDPARAMSENTRY._serialized_options = b'8\001'
  _BUILDREQUEST._serialized_start=55
  _BUILDREQUEST._serialized_end=505
  _BUILDREQUEST_ENVVARSENTRY._serialized_start=407
  _BUILDREQUEST_ENVVARSENTRY._serialized_end=453
  _BUILDREQUEST_BUILDPARAMSENTRY._serialized_start=455
  _BUILDREQUEST_BUILDPARAMSENTRY._serialized_end=505
  _SCMREVISION._serialized_start=507
  _SCMREVISION._serialized_end=612
  _MULTISCMREVISION._serialized_start=614
  _MULTISCMREVISION._serialized_end=707
  _GITHUBSCMREVISION._serialized_start=710
  _GITHUBSCMREVISION._serialized_end=851
# @@protoc_insertion_point(module_scope)
