# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kokoro_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="kokoro_api.proto",
    package="devtools.kokoro.api.proto",
    syntax="proto2",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x10kokoro_api.proto\x12\x19\x64\x65vtools.kokoro.api.proto"\xc2\x03\n\x0c\x42uildRequest\x12\x15\n\rfull_job_name\x18\x01 \x01(\t\x12<\n\x0cscm_revision\x18\x03 \x01(\x0b\x32&.devtools.kokoro.api.proto.ScmRevision\x12G\n\x12multi_scm_revision\x18\t \x01(\x0b\x32+.devtools.kokoro.api.proto.MultiScmRevision\x12\x18\n\x10input_file_paths\x18\x04 \x03(\t\x12\x46\n\x08\x65nv_vars\x18\x06 \x03(\x0b\x32\x34.devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry\x12N\n\x0c\x62uild_params\x18\x0c \x03(\x0b\x32\x38.devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x42uildParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"i\n\x0bScmRevision\x12K\n\x13github_scm_revision\x18\x04 \x01(\x0b\x32,.devtools.kokoro.api.proto.GithubScmRevisionH\x00\x42\r\n\x0bscmrevision"]\n\x10MultiScmRevision\x12I\n\x13github_scm_revision\x18\x04 \x03(\x0b\x32,.devtools.kokoro.api.proto.GithubScmRevision"\x8d\x01\n\x11GithubScmRevision\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\ncommit_sha\x18\x01 \x01(\t\x12\x1b\n\x13pull_request_number\x18\x02 \x01(\t\x12\x16\n\x0erepository_url\x18\x03 \x01(\t\x12\r\n\x05owner\x18\x05 \x01(\t\x12\x12\n\nrepository\x18\x06 \x01(\t',
)


_BUILDREQUEST_ENVVARSENTRY = _descriptor.Descriptor(
    name="EnvVarsEntry",
    full_name="devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=400,
    serialized_end=446,
)

_BUILDREQUEST_BUILDPARAMSENTRY = _descriptor.Descriptor(
    name="BuildParamsEntry",
    full_name="devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry.key",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry.value",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"8\001",
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=448,
    serialized_end=498,
)

_BUILDREQUEST = _descriptor.Descriptor(
    name="BuildRequest",
    full_name="devtools.kokoro.api.proto.BuildRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="full_job_name",
            full_name="devtools.kokoro.api.proto.BuildRequest.full_job_name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="scm_revision",
            full_name="devtools.kokoro.api.proto.BuildRequest.scm_revision",
            index=1,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="multi_scm_revision",
            full_name="devtools.kokoro.api.proto.BuildRequest.multi_scm_revision",
            index=2,
            number=9,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="input_file_paths",
            full_name="devtools.kokoro.api.proto.BuildRequest.input_file_paths",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="env_vars",
            full_name="devtools.kokoro.api.proto.BuildRequest.env_vars",
            index=4,
            number=6,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="build_params",
            full_name="devtools.kokoro.api.proto.BuildRequest.build_params",
            index=5,
            number=12,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _BUILDREQUEST_ENVVARSENTRY,
        _BUILDREQUEST_BUILDPARAMSENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=48,
    serialized_end=498,
)


_SCMREVISION = _descriptor.Descriptor(
    name="ScmRevision",
    full_name="devtools.kokoro.api.proto.ScmRevision",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="github_scm_revision",
            full_name="devtools.kokoro.api.proto.ScmRevision.github_scm_revision",
            index=0,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="scmrevision",
            full_name="devtools.kokoro.api.proto.ScmRevision.scmrevision",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=500,
    serialized_end=605,
)


_MULTISCMREVISION = _descriptor.Descriptor(
    name="MultiScmRevision",
    full_name="devtools.kokoro.api.proto.MultiScmRevision",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="github_scm_revision",
            full_name="devtools.kokoro.api.proto.MultiScmRevision.github_scm_revision",
            index=0,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=607,
    serialized_end=700,
)


_GITHUBSCMREVISION = _descriptor.Descriptor(
    name="GithubScmRevision",
    full_name="devtools.kokoro.api.proto.GithubScmRevision",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="devtools.kokoro.api.proto.GithubScmRevision.name",
            index=0,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="commit_sha",
            full_name="devtools.kokoro.api.proto.GithubScmRevision.commit_sha",
            index=1,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="pull_request_number",
            full_name="devtools.kokoro.api.proto.GithubScmRevision.pull_request_number",
            index=2,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="repository_url",
            full_name="devtools.kokoro.api.proto.GithubScmRevision.repository_url",
            index=3,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="owner",
            full_name="devtools.kokoro.api.proto.GithubScmRevision.owner",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="repository",
            full_name="devtools.kokoro.api.proto.GithubScmRevision.repository",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=703,
    serialized_end=844,
)

_BUILDREQUEST_ENVVARSENTRY.containing_type = _BUILDREQUEST
_BUILDREQUEST_BUILDPARAMSENTRY.containing_type = _BUILDREQUEST
_BUILDREQUEST.fields_by_name["scm_revision"].message_type = _SCMREVISION
_BUILDREQUEST.fields_by_name["multi_scm_revision"].message_type = _MULTISCMREVISION
_BUILDREQUEST.fields_by_name["env_vars"].message_type = _BUILDREQUEST_ENVVARSENTRY
_BUILDREQUEST.fields_by_name[
    "build_params"
].message_type = _BUILDREQUEST_BUILDPARAMSENTRY
_SCMREVISION.fields_by_name["github_scm_revision"].message_type = _GITHUBSCMREVISION
_SCMREVISION.oneofs_by_name["scmrevision"].fields.append(
    _SCMREVISION.fields_by_name["github_scm_revision"]
)
_SCMREVISION.fields_by_name[
    "github_scm_revision"
].containing_oneof = _SCMREVISION.oneofs_by_name["scmrevision"]
_MULTISCMREVISION.fields_by_name[
    "github_scm_revision"
].message_type = _GITHUBSCMREVISION
DESCRIPTOR.message_types_by_name["BuildRequest"] = _BUILDREQUEST
DESCRIPTOR.message_types_by_name["ScmRevision"] = _SCMREVISION
DESCRIPTOR.message_types_by_name["MultiScmRevision"] = _MULTISCMREVISION
DESCRIPTOR.message_types_by_name["GithubScmRevision"] = _GITHUBSCMREVISION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildRequest = _reflection.GeneratedProtocolMessageType(
    "BuildRequest",
    (_message.Message,),
    {
        "EnvVarsEntry": _reflection.GeneratedProtocolMessageType(
            "EnvVarsEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _BUILDREQUEST_ENVVARSENTRY,
                "__module__": "kokoro_api_pb2"
                # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.BuildRequest.EnvVarsEntry)
            },
        ),
        "BuildParamsEntry": _reflection.GeneratedProtocolMessageType(
            "BuildParamsEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _BUILDREQUEST_BUILDPARAMSENTRY,
                "__module__": "kokoro_api_pb2"
                # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.BuildRequest.BuildParamsEntry)
            },
        ),
        "DESCRIPTOR": _BUILDREQUEST,
        "__module__": "kokoro_api_pb2"
        # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.BuildRequest)
    },
)
_sym_db.RegisterMessage(BuildRequest)
_sym_db.RegisterMessage(BuildRequest.EnvVarsEntry)
_sym_db.RegisterMessage(BuildRequest.BuildParamsEntry)

ScmRevision = _reflection.GeneratedProtocolMessageType(
    "ScmRevision",
    (_message.Message,),
    {
        "DESCRIPTOR": _SCMREVISION,
        "__module__": "kokoro_api_pb2"
        # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.ScmRevision)
    },
)
_sym_db.RegisterMessage(ScmRevision)

MultiScmRevision = _reflection.GeneratedProtocolMessageType(
    "MultiScmRevision",
    (_message.Message,),
    {
        "DESCRIPTOR": _MULTISCMREVISION,
        "__module__": "kokoro_api_pb2"
        # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.MultiScmRevision)
    },
)
_sym_db.RegisterMessage(MultiScmRevision)

GithubScmRevision = _reflection.GeneratedProtocolMessageType(
    "GithubScmRevision",
    (_message.Message,),
    {
        "DESCRIPTOR": _GITHUBSCMREVISION,
        "__module__": "kokoro_api_pb2"
        # @@protoc_insertion_point(class_scope:devtools.kokoro.api.proto.GithubScmRevision)
    },
)
_sym_db.RegisterMessage(GithubScmRevision)


_BUILDREQUEST_ENVVARSENTRY._options = None
_BUILDREQUEST_BUILDPARAMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
